//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_SalePhone_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class colorproduct
    {
        public int cop_id { get; set; }
        public int prod_id { get; set; }
        public int co_id { get; set; }
    
        public virtual colorlist colorlist { get; set; }
        public virtual product product { get; set; }
    }
}
