//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_SalePhone_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int cus_id { get; set; }
        public string cus_name { get; set; }
        public int cus_phone { get; set; }
        public string cus_email { get; set; }
        public string cus_address { get; set; }
    }
}
